### ISSUE TITLE
Pruebas Unitarias 

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/practica-6-de-pruebas-unitarias-tecnopower#1]
[PRACTICA 6_PRUEBAS_UNITARIAS_DE_CONTRATOS_INTELIGENTES.pdf](https://github.com/SistemasTecTlaxiaco/practica-6-de-pruebas-unitarias-tecnopower/files/8866154/PRACTICA.6_PRUEBAS_UNITARIAS_DE_CONTRATOS_INTELIGENTES.pdf)

**Comment by Rmz-Rigo** [comment]
CALIFICACION: 20/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
